# Generated by Django 6.0.4 on 2026-04-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoleBasedAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_instructor_dashboard', 'Can view instructor dashboard')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
