# Generated by Django 6.0.4 on 2026-04-17 08:46

import shema.models
import shema.upload_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shema', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to=shema.models.avatar_upload_path, validators=[shema.upload_validators.validate_avatar]),
        ),
        migrations.AddField(
            model_name='profile',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=shema.models.document_upload_path, validators=[shema.upload_validators.validate_document]),
        ),
    ]
